-- CreateTable
CREATE TABLE "SlackAppInstallation" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "clientId" TEXT,
    "appId" TEXT,
    "enterpriseId" TEXT,
    "enterpriseName" TEXT,
    "enterpriseUrl" TEXT,
    "teamId" TEXT,
    "teamName" TEXT,
    "botToken" TEXT,
    "botId" TEXT,
    "botUserId" TEXT,
    "botScopes" TEXT,
    "botRefreshToken" TEXT,
    "botTokenExpiresAt" DATETIME,
    "userId" TEXT,
    "userToken" TEXT,
    "userScopes" TEXT,
    "userRefreshToken" TEXT,
    "userTokenExpiresAt" DATETIME,
    "incomingWebhookUrl" TEXT,
    "incomingWebhookChannel" TEXT,
    "incomingWebhookChannelId" TEXT,
    "incomingWebhookConfigurationUrl" TEXT,
    "isEnterpriseInstall" BOOLEAN NOT NULL DEFAULT false,
    "tokenType" TEXT NOT NULL DEFAULT 'bot',
    "installedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
